#+title: Musa's Quotes

* Imam Ali Quotes
** How strange and foolish is man.                                 :use_body:

                        How strange and foolish is man.
                     He loses his health in gaining wealth.
                  Then to regain health he wastes his wealth.
              He ruins his present while worrying about his future
                – but weeps in the future by recalling his past.
                He lives as though death shall never come to him
                 – but dies in a way as if he were never born.

                                   --Imam Ali

** Everyone who is taken by death asks for more time, while everyone who still has time makes excuses for procrastination. --Imam Ali
** Courtesy costs nothing, but buys everything. --Imam Ali
** Silence is the garden of thought. --Imam Ali
** The best revenge is to improve yourself. --Imam Ali
** To fight against one’s desires is the greatest of all fights. --Imam Ali
** Any day on which you don’t commit sins or disobey Allah is a day of celebration (Eid). --Imam Ali
** If you don’t endure the difficulties of working, you are made to bear the misfortunes of poverty. --Imam Ali
** Don’t worry about how fast you do a job; instead, observe the best quality in whatever you do. --Imam Ali
** It’s beneath you to make a promise to your child and not keep it. --Imam Ali
** Enjoy your moments of happiness with all your heart to help you at the time of sadness. --Imam Ali
** Surely, silence can sometimes be the most eloquent reply. --Imam Ali
** Beware of speaking too much, for it increases mistakes and engenders boredom. --Imam Ali
** A wise man first thinks and then speaks and a fool speaks first and then thinks. --Imam Ali
** Lead such a life, that, when you die, the people may mourn you, and while you are alive they long for your company. --Imam Ali
** Do not feel lonely on the road of righteousness because of the fewness of the walkers on it. --Imam Ali
** Fear God and you will have no cause to fear any one. --Imam Ali
** The word of God is the medicine of the heart. --Imam Ali
** The days of life pass away like clouds, so do good while you are alive. --Imam Ali
** Opportunity is swift of flight but slow to return. --Imam Ali
** He who knows himself knows God. --Imam Ali
** Do not soil your conscience for anything but heaven --Imam Ali
** To fight against one’s desires is the greatest of all fights. --Imam Ali
** The strongest amongst you is he who subdues his self. --Imam Ali
** Riches without faith are the greatest poverty. --Imam Ali
** A man’s worth depends upon the nobility of his aspirations. --Imam Ali
** Generosity hides shortcomings. --Imam Ali
** The wealth of a miser is as useless as a pebble. --Imam Ali
** Desire is one’s most inveterate enemy. --Imam Ali
** Patience is the fruit of faith. --Imam Ali
** No shelter is safer than piety. --Imam Ali
** A man’s behavior is the index of his mind. --Imam Ali
** To seek counsel is to go to the fountain of guidance. --Imam Ali
** Silence is the best reply to a fool. --Imam Ali
** The best speech is one that is short and reasonable. --Imam Ali
** Speech is like a medicine, a small dose of which cures but an excess of which kills. --Imam Ali
** He that has no courage has no religion. --Imam Ali
** His grief is long whose hope is short. --Imam Ali
** The right of freedom of speech consists in speaking the truth. --Imam Ali
** To assist the wrong is to oppress the right. --Imam Ali
** He who seeks to do justice with men, let him desire for them what he desires for himself. --Imam Ali
** The greatest sin is the sin that the sinner considers to be ordinary. --Imam Ali
** Contentment is the asset which is never exhausted. --Imam Ali
** Contentment is the treasure which is never exhausted. --Imam Ali
** Governments are a trial for men. --Imam Ali
** Haste is a species of madness. --Imam Ali
** Anger is a fire kindled, he who restrains anger extinguishes the fire; he who gives vent to it is the first to be consumed by such fire. --Imam Ali
** Truth is bitter, but its result is sweet; falsehood appears to be sweet but it is poisonous in its effect. --Imam Ali
** Knowledge and practice are twins, and both go together. There is no knowledge without practice, and no practice without knowledge. --Imam Ali
** He who does not know should not be ashamed to learn. --Imam Ali
** Patience is to faith, what head is to the body. When patience goes, faith goes, when head goes, the body goes. --Imam Ali
** A good disposition is the best companion. --Imam Ali
** He who is aware of his own faults is oblivious of the faults of others. --Imam Ali
** Do not have too many irons in the fire; concentrate on one thing at a time. --Imam Ali
** What you do not like for your self, do not like it for others. --Imam Ali
** The advice of old men is dearer than the bravery of young men. --Imam Ali
** That knowledge is superficial which is merely on the tongue. That knowledge is real which demonstrates itself in your practice. --Imam Ali
** Waste of time is one’s greatest loss. --Imam Ali
** He who knows to keep his secret knows the way to success. --Imam Ali
** Foresight is the way to safety. --Imam Ali
** Enlighten the heart with prayers. --Imam Ali
** In all that you do seek the protection of God. --Imam Ali
** Do not become a slave of your desires. --Imam Ali
** Whatever harm accrues of silence can be remedied but whatever harm is done because of speech cannot be remedied. --Imam Ali
** It is better to restrain your desires than to stretch your hand before others. --Imam Ali
** A wise man takes a lesson even from a minor lapse. --Imam Ali
** You are master of what you say until you utter it, --Imam Ali   :use_body:

               You are master of what you say until you utter it,
                   once you deliver it, you are its captive.
              Preserve your tongue as you do your gold and money.
         One word could bring disgrace and the termination of a bliss.
                                   --Imam Ali
** Overpower desires and suspicions by patience and faith. --Imam Ali
* [[https://al-islam.org/nahjul-balagha-part-2-letters-and-sayings][Nahjul Balagha, “The Peak of Eloquence”]]
:PROPERTIES:
:CREATED:  [2025-05-19 Mon 06:53]
:END:
** How wonderful is man that sees with fat, talks with a piece of flesh, hears with a bone and breathes through a hole.
:PROPERTIES:
:CREATED:  [2025-05-19 Mon 06:53]
:Source:   https://al-islam.org/nahjul-balagha-part-2-letters-and-sayings/selections-sayings-and-preaching-amir-al-muminin-ali#hadith-n-8
:END:

 قَال عليه السلام : اعْجَبُوا لِهذَا الاْنْسَانِ يَنْظُرُ بِشَحْمٍ و يَتَكَلَّم بِلَحْمٍ وَيَسْمَعُ بِعَظْمٍ، وَيَتَنَفَّسُ
مِنْ خَرْمٍ
*** Meet people in such a manner that if you die they should weep for you and if you live they should long for you.
:PROPERTIES:
:CREATED:  [2025-05-19 Mon 06:56]
:Source:   https://al-islam.org/nahjul-balagha-part-2-letters-and-sayings/selections-sayings-and-preaching-amir-al-muminin-ali#hadith-n-10
:END:

 وَ قَالَ عليه‏السلام: خَالِطُوا النَّاسَ مُخَالَطَةً إِنْ مِتُّمْ مَعَهَا بَكَوْا عَلَيْكُمْ وَ إِنْ عِشْتُمْ حَنُّوا إِلَيْكُمْ.
*** The most helpless of all men is he who cannot find a few brothers during his life, but still more helpless. is he who finds such a brother but loses him. :Friendship:
:PROPERTIES:
:CREATED:  [2025-05-19 Mon 06:57]
:Source:   https://al-islam.org/nahjul-balagha-part-2-letters-and-sayings/selections-sayings-and-preaching-amir-al-muminin-ali#hadith-n-12
:END:
12. وَ قَالَ عليه‏السلام: أَعْجَزُ النَّاسِ مَنْ عَجَزَ عَنِ اكْتِسَابِ الْإِخْوَانِ وَ أَعْجَزُ مِنْهُ مَنْ ضَيَّعَ مَنْ ظَفِرَ بِهِ مِنْهُمْ
* Imam Husayn Quotes
** Do not say something which would undermine your self-worth. --Imam Husayn
** Gain people’s praise with your efforts and successes, and do not expose yourself to people’s blames through laziness and lethargy. --Imam Husayn
** Hastiness is foolishness. --Imam Husayn
** When a poor man begs for your help, his pride is hurt. Then you don’t deal another blow to his pride by letting him down. --Imam Husayn
** Visiting relatives and keeping in touch with them will bring you a longer and more substantial life. --Imam Husayn
** Observe your physical health in your lifetime. --Imam Husayn
**                     You deserve Paradise.                       :use_body:

                             You deserve Paradise.
                     Don’t sell yourself for anything less.
Whoever is content to worldly pleasures, has sufficed to something base and low.

                                 --Imam Husayn

* Quran Quotes
** Surely in the remembrance of God are hearts eased. --Quran 13:28
** God does not burden any soul with more than it can bear. --Quran 2:286
** Indeed, 𝐼 am near. --Quran 2:186
** Do you suppose that you will enter the Garden                   :use_body:

                 Do you suppose that you will enter the Garden
              without first having suffered like those before you?
                They were afflicted by misfortune and hardship,
              and they were so shaken that even [their] messenger
        and the believers with him cried, ‘When will God’s help arrive?’
                          Truly, God’s help is near.”
                                 --Quran 2:214

** Whoever does an atom’s weight of good will see it. --Quran 99:7
** Say, ‘[God says], My servants who have harmed yourselves by your own excess, :use_body:

  Say, ‘[God says], My servants who have harmed yourselves by your own excess,
             do not despair of God’s mercy. God forgives all sins:
              He is truly the Most Forgiving, the Most Merciful.’
                                 --Quran 39:53

** When those who believe in Our revelations come to you [Prophet], say, :use_body:

     When those who believe in Our revelations come to you [Prophet], say,
     ‘Peace be upon you. Your Lord has taken it on Himself to be merciful:
      if any of you has foolishly done a bad deed, and afterwards repented
     and mended his ways, God is most Forgiving and most Merciful.” [Quran
                                     6:54]

* Semi-Hilarious Ways to Indulge in Positive Self-Talk
** When you start to number anything,  think, “I’m the number one most awesome person.”
** When you see a dessert (or eat one),  think, “Almost as sweet as me.”
** When you grab a cold drink,  think, “Almost as cool as I am.”
** When you’re getting a coffee, think, “I, too, perk people up.”
** When you eat your vegetables, tell yourself, “You know what else is good for people? Me.”
** When you first wake up in the morning, think, “This day is going to be awesome. Why? Because I’m in it.”
** When you finish getting dressed and you look in the mirror, say out loud, “Damn, you look good.”
** As you brush your teeth, remind yourself, “It’s a good thing I’m taking care of my amazing smile.”
** When you see the number 10, think, “I score a perfect 10 in being a human being.”
** Did something make you laugh? Then say to yourself, “I have a great sense of humour.”
** When you flip on a light switch, think, “My personality also lights up a room.”
** Did you trip or fall down? Don’t tell yourself you’re a klutz. Instead, think, “When I stumble, I just keep on going.”
** If you’re clumsy and awkward, think, “I’m just like the cute main character in a romantic comedy.”
** Putting an address in Waze or Google Maps? Think, “Of course, my eventual destination is greatness.”
** Running late? Try thinking this: “Well, at least I’m worth waiting for.”
** If you’re sitting down to write out a to-do list, remind yourself, “I can do anything I set my mind to.”
** If you’re trying to find your way in a mall, a zoo, etc., think, “This place is a maze…but that’s okay, because I’m a-maze-ing.”
** When you see or hear a police car, think, “Uh-oh, somebody called the police, because I am killing it today.”
** When you see or hear a fire truck, think, “Someone called the fire department, because I’m smoking hot.”
** When a server at a restaurant sets down a plate in front of you and says, “Careful, that’s hot,” think, “So am I.”
** Is your phone out of juice? Think, “Well, at least I’m powerful.”
** When you see a cute dog or cat, tell yourself, “They’re so loveable…just like me.”
** When you finish a workout…even a teeny tiny, beginner one… think, “Yep, I’m a champion.”
** When you see a poster or a movie trailer about a superhero, tell yourself, “I also use my incredible powers for good.”
** When you see a picture of Santa Claus, think, “I, too, can get a lot accomplished in just one evening.”
** If you’re about to eat a banana, think, “This is so appropriate, because I’m really appealing.”
** If you’re on an elevator going up, tell yourself, “I’m also taking my life to a whole new level.”
** Someone’s talking about a wildly expensive item. Remind yourself, “That’s nothing compared to how valuable I am.”
** If you’re using a kitchen knife —or a needle— think, “I’m also sharp.”
** When you see a crown…or come across a headline about royals… think, “Sometimes, it’s hard to hide the fact that I’m a king 🫅”
** When you see a picture of a swan, think, “Almost as graceful as me.”
** When you see a picture of a bull, think, “Almost as strong as me.”
** When the stars are out, think, “I can’t see enough stars in the sky for all my wishes that are going to come true.”
** When someone pays you a compliment, think to yourself, “They got that right.”
** When everyone’s excited because it’s pumpkin spice season, think how lucky everyone is that you’re around all year.
** When you walk into a party, think to yourself, “Well, this party just got a lot more fun.”
** Take a deep breath in and think, “I’m breathing in positivity.” Exhale and think, “I’m releasing negativity.”
** Looking ahead on your calendar to the coming week…or month…or year? Say, “This is going to be the best (week/month/year) EVER.”
** When the forecast calls for rain, think, “That’s okay. I bring the sunshine wherever I go.”
** When you put on your sunglasses, think, “My future’s so bright, I’ve got to wear shades.”
** When you go to bed at night, think, “I can’t wait for tomorrow, because I get more awesome every day.”
** I'm so hilarious sometimes I crack myself up
** I shine so brilliantly, diamonds get jealous
* Positive Affirmations
** I am worth the effort it takes to eat healthy food and get exercise.
** I am worth a high salary.
** I make everyday into an adventure.
** I deserve an abundant life.
** I am grateful for what I have today.
** I am conquering my addictions.
** I am worth the effort it takes to eat healthy food and get exercise.
** I am loved by many family members and friends.
** I’m good at making others feel accepted.
** I enjoy listening to people, and they appreciate my good listening skills.
** People enjoy my company.
** With every deep breath in, I breathe in positivity;  with every breath out, I breathe out anxiety.
** I am grateful for the blessings the future holds for me.
** I am grateful for the blessings I enjoy now.
** I am supported by God above and by those who love me.
** I have peace in my mind and love in my heart.
** I am safe and secure.
** I’m proud of myself for having the courage to try.
** I forgive myself for my mistakes  and  I’m going to learn from them.
** I deserve the success coming my way.
** I trust my training and the work I’ve put in; I will reach my goals.
** I’ve been working hard and now I deserve some rest!
** I’m doing my best and that is all that matters.
** My body is strong and capable of doing amazing things.
** I don’t have to be perfect,  I just have to be willing to try.
** I’m on the right track.
** I can always get better.
** I’m so grateful for this opportunity.
** This challenge is an opportunity to grow.
* Misc
** “Any time” ≈ “no time”
** You don’t stop laughing because you grow old:  You grow old because you stop laughing.
** I work only to support my lifestlye: To spend as much time as possible with my kids outdoors!
** Make every hour as productive as possible, so that I can spend time with my kids 👧🏻‍👦🏻
** “Your beliefs become your thoughts, Your thoughts become your words, Your words become your actions, Your actions become your habits, Your habits become your values, Your values become your destiny.” — Mahatma Gandhi
* What do you mean “Good morning?”? Do you wish me a good morning, or mean that it is a good morning whether I want it or not; or that you feel good this morning; or that it is a morning to be good on?"
:PROPERTIES:
:CREATED:  [2026-04-27 Mon 11:06]
:END:
* Stress                                                           :use_body:
:PROPERTIES:
:CREATED:  [2025-04-30 Wed 11:40]
:END:

A wise man once told me, “if you don't schedule a break, your body will take one
            for you. And it probably won't be at a convenient time.”
* Life Purpose                                                     :use_body:
:PROPERTIES:
:CREATED:  [2025-05-20 Tue 08:48]
:END:

                     When people say “What are you doing?”,
                        You say ⟪Things that please me.⟫
                          They say “Toward what end?”,
                            and you say ⟪Pleasure.⟫
                They say “But really, what are you working on?”
                         You say ⟪Having a good time!⟫
* Computing Science
** Elegance is not a dispensable luxury but a quality that decides between success and failure. - Edsger W. Dijkstra
** If we wish to count lines of code, we should not regard them as ‘lines produced’ but as ‘lines spent.’ - Edsger Dijkstra
** We flew down weekly to meet with IBM, but they thought the way to measure software was the amount of code we wrote, when really the better the software, the fewer lines of code. - Bill Gates
** Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates
** Computing science is no more about computers than astronomy is about telescopes. - Edsger W. Dijkstra
** I don’t need to waste my time with a computer just because I am a computer scientist. - Edsger W. Dijkstra
** People think that computer science is the art of geniuses but the actual reality is the opposite, just many people doing things that build on each other, like a wall of mini stones. - Donald Knuth
** Some problems are better evaded than solved. - C. A. R. Hoare
** Software is not limited by physics, like buildings are. It is limited by imagination, by design, by organization. In short, it is limited by properties of people, not by properties of the world. - Ralph Johnson
** A list is only as strong as its weakest link. - Donald Knuth
** One man’s constant is another man’s variable. - Alan J. Perils
** Controlling complexity is the essence of computer programming. - Brian W. Kernighan
** Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases. - Norman Augustine
** Software is a gas; it expands to fill its container. - Nathan Myhrvold
** Imagination is more important than knowledge.  For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution. - Albert Einstein
** The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. - Stephen Hawking
** Program testing can be a very effective way to show the presence of bugs, but is hopelessly inadequate for showing their absence. - Edsger Dijkstra
** There are only two things wrong with C++:  The initial concept and the implementation. - Bertrand Meyer
** More good code has been written in languages denounced as "bad" than in languages proclaimed "wonderful" -much more. - Bjarne Stroustrup
** There are only two kinds of languages: the ones people complain about and the ones nobody uses. - Bjarne Stroustrup
** Beware of bugs in the above code; I have only proved it correct, not tried it.  - Donald Knuth
** The question of whether computers can think is like the question of whether submarines can swim. - Edsger W. Dijkstra
** Being abstract is something profoundly different from being vague... The purpose of abstraction is not to be vague, but to create a new semantic level in which one can be absolutely precise. - Edsger Dijkstra
** Considering the current sad state of our computer programs, software development is clearly still a black art, and cannot yet be called an engineering discipline. - Bill Clinton'
* Random
** 3 out of 4 people make up 75% of the population.
** A day for firm decisions! Or is it?
** A device that will cut your fuel bills in half - scissors
** A government that robs Peter to pay Paul can always depend on the support of Paul. --George Bernard Shaw
** A sentence is something you should never put a preposition at the end of.
** A signature always reveals a man's character - and sometimes even his name.
** Always remember you're unique, just like everyone else.
** Before you criticize someone, you should walk a mile in their shoes. That way, when you criticize them, you're a mile away, and you have their shoes
** Boomerangs are coming back, Ski slopes are going downhill, but Exit signs are on the way out.
** Democracy is four wolves and a lamb voting on what to have for lunch.
** Don't use a big word where a diminutive one will suffice.
** Everyone is someone else's weirdo.
** Experience is something you get just after you need it.
** Grandma used to say Money is not the key to happiness. If you have money you can always have a key made.
** I am not young enough to know everything. -- Oscar Wilde
** If you tell the truth, you don't have to remember anything.
** If it weren't for the last minute, nothing would get done.
** If today is the first day of the rest of your life, what was yesterday?
** It doesn't matter how you get there if you don't know where you're going.
** It is dangerous to be right in matters on which the established authorities are wrong. --Voltaire
** Life is what happens to you while you're busy making other plans. -- John Lennon
** Millions yearn for immortality who don't know what to do with themselves on a rainy Sunday afternoon. -- Susan Ertz
** Never ask a barber if he thinks you need a haircut.
** Never attribute to malice what can be adequately explained by stupidity.
** The early bird gets the worm, but the early worm gets eaten.
** When a stupid man is doing something he is ashamed of, he always declares that it is his duty. --George Bernard Shaw
** It's important to have an open mind, but not so open that your brains fall out.
** The DOPELER Effect is the tendency of stupid ideas to seem smarter when they come at you rapidly
** I always win. Except when I lose, but then I just don't count it.
** The trouble with doing something right the first time, is nobody appreciates how difficult it was.
** When I was born, I was so surprised, I couldn't talk for a year and a half!
** There are two rules for success... 1) Never tell everything you know. 
** Be nice to other people; they outnumber you 5.5 billion to one. 
** Even if you're on the right track, you'll get run over if you just sit there. --Will Rogers
** The only reason some people get lost in thought because it is unfamiliar territory.
** Talk is cheap because supply exceeds demand
** Half of the people in the world are below average. 
** Male zebras have white stripes, female zebras have black stripes.
** Even if you win the rat race, you're still a rat. 
** Natives who beat drums to drive off evil spirits are objects of scorn to smart people who blow horns to break up traffic jams.
** All sweeping generalisations are wrong.
** My sources are unreliable, but their information is fascinating.
** When you find yourself in a hole, the first thing to do is stop digging.
** Never explain -- your Friends do not need it and your enemies will not believe you anyway.
** If it's stupid but works, it isn't stupid.
** It is a miracle that curiosity survives formal education. -- Albert Einstein
** All that is necessary for the forces of evil to take root in the world is for enough good men to do nothing. -- Edmund Burke
** People will accept your ideas much more readily if you tell them Benjamin Franklin said it first.
** The two most common elements in the universe are hydrogen and stupidity. --Isaac Asimov
** Compromise is the art of dividing a cake so everyone believes he got the biggest piece. --Ludwig Erhard
** It is the nature of emergencies to be inconvenient. --Terri Weiner
** Opportunity is missed by most people because it is dressed in overalls and looks like work. --Thomas Edison
** It's better to be boldly decisive and risk being wrong than to agonize at length and be right too late. --Marilyn Kennedy
** A good plan today is better than a perfect plan tomorrow. -Gen. George Patton
** It is better to have enough ideas for some of them to be wrong than to always be right by having no ideas at all. --Edward de Bono
** Time is what keeps everything from happening all at once.
** Tell a man there are 300 billion stars in the universe and he'll believe you. Tell him a seat has wet paint on it and he'll have to touch it to be sure.
** I have not failed. I've just found 10,000 ways that won't work. -- Thomas Alva Edison
** There is no surer way to ruin a good discussion than to contaminate it with facts.
** For business reasons, I must maintain the outward signs of sanity. --Mark Twain
** There is nothing either good or bad, but thinking makes it so. -- Shakespeare
** Thirty-five is when you finally get your head together and your body starts falling apart.
** The tragedy of life doesn't lie in not reaching your goal. The tragedy lies in having no goal to reach.
** [#A] What if, at this very moment, you are living up to your full potential?
** Never say OOPS! always say Ah, Interesting!
** Everything that can be invented has been invented. --Charles H. Duell, Commissioner, U.S. Office of Patents, 1899.
** The abdomen, the chest, and the brain will forever be shut from the intrusion of the wise and humane surgeon. -Sir John Eric Ericksen, British surgeon, appointed Surgeon-Extraordinary to Queen Victoria 1873.
** Louis Pasteur's theory of germs is ridiculous fiction.'-Pierre Pachet, Professor of Physiology at Toulouse, 1872
** Who the hell wants to hear actors talk? --H.M. Warner, Warner Brothers, 1927.
** Heavier-than-air flying machines are impossible. --Lord Kelvin, president, Royal Society, 1895.
